### ISSUE TITLE
Flickr HTML breaks PDF generation

### ISSUE THREAD

**Issue by hanleybrand** [hanleybrand/rooibos#15]
HTML in fields that is imported via Flickr containing rel="NOFOLLOW" (and potentially other uncommon HTML tags) breaks PDF generation for 

example field/value pair: 

```javascript
{'value': u'The original image was found at\n<a href="http://www.toutfait.com/images/GalleryImage/Big_Gallery_Image_146.jpg" rel="nofollow">www.toutfait.com/images/GalleryImage/Big_Gallery_Image_14...</a>\n\nThe image linked here is claimed to be used under fair use as:\n\n1. It is a historically significant artwork.\n2. The image is only being used for informational purposes.\n3. Its inclusion in the wiki adds significantly to the wiki because it illustrates the subject of this wiki and how the image depicted is familiar to the general public.\n4. The image is readily available on the internet.\n5. It is a low resolution image.\n6. It is not believed that this use will cause commercial harm to the copyright holder.', 'label': u'Description'}
```

Traceback:

```
Traceback (most recent call last):

 File "~/django/core/handlers/base.py", line 100, in get_response
   response = callback(request, *callback_args, **callback_kwargs)

 File "~/rooibos/viewers/views.py", line 20, in viewer_shell
   response = viewer.view(request)

 File "~/rooibos/presentation/viewers.py", line 177, in view
   drawCard(index, item)

 File "~/rooibos/presentation/viewers.py", line 159, in drawCard
   data.append(getParagraph('<b>%s:</b> %s' % (value.resolved_label, v), styles['Data']))

 File "~/rooibos/presentation/viewers.py", line 134, in getParagraph
   return Paragraph(*args, **kwargs)

 File "~/site-packages/reportlab-2.5-py2.6-linux-i686.egg/reportlab/platypus/paragraph.py", line 827, in __init__
   self._setup(text, style, bulletText, frags, cleanBlockQuotedText)

 File "~/site-packages/reportlab-2.5-py2.6-linux-i686.egg/reportlab/platypus/paragraph.py", line 845, in _setup
   % (_parser.errors[0],text[:min(30,len(text))]))

ValueError: xml parser error (invalid attribute name rel) in paragraph beginning
'<b>Description:</b> Floating P'
```

**Comment by hanleybrand** [comment]
quick fix: 

```python
def remove_rels_from_a_tags(fragment):
    log.debug('cleaned value = %s' % fragment)

    soup = BeautifulSoup(fragment, 'lxml')
    for next_rel in soup.find_all("a", rel=True):
        del next_rel['rel']

    return soup.body.next
```
