### ISSUE TITLE
rooibos.access.AccessOnStart:  Duplicate key name 'access_accesscontrol_846f0221'

### ISSUE THREAD

**Issue by hanleybrand** [hanleybrand/rooibos#7]
The main issue might be that rooibos.access.middleware.AccessOnStart isn't removed after initialization (it's supposed to be)

 
``` 
DEBUG [u'CREATE INDEX `access_accesscontrol_846f0221` ON `access_accesscontrol` (`object_id`);']
DEBUG .AccessOnStart: Add missing index on object_id on AccessControl table
running query CREATE INDEX `access_accesscontrol_846f0221` ON `access_accesscontrol` (`object_id`);
ERROR access.middleware: error running query
                              is it access_accesscontrol_846f0221?
```

**spoiler alert: YES**

```
InternalError: (1061, u"Duplicate key name 'access_accesscontrol_846f0221'")
Traceback (most recent call last):
  File "/Users/hanley/Dev/hacking-mdid3/rooibos/access/middleware.py", line 34, in __init__
    cursor.execute(s)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/cursors.py", line 134, in execute
    result = self._query(query)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/cursors.py", line 282, in _query
    conn.query(q)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 768, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 929, in _read_query_result
    result.read()
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 1125, in read
    first_packet = self.connection._read_packet()
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 893, in _read_packet
    packet.check_error()
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 369, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1061, u"Duplicate key name 'access_accesscontrol_846f0221'")
```

```
ERROR rooibos.AccessControl.object_id
Traceback (most recent call last):
  File "/Users/hanley/Dev/hacking-mdid3/rooibos/access/middleware.py", line 34, in __init__
    cursor.execute(s)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/cursors.py", line 134, in execute
    result = self._query(query)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/cursors.py", line 282, in _query
    conn.query(q)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 768, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 929, in _read_query_result
    result.read()
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 1125, in read
    first_packet = self.connection._read_packet()
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 893, in _read_packet
    packet.check_error()
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 369, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1061, u"Duplicate key name 'access_accesscontrol_846f0221'")
ERROR (1061, u"Duplicate key name 'access_accesscontrol_846f0221'")
Traceback (most recent call last):
  File "/Users/hanley/Dev/hacking-mdid3/rooibos/access/middleware.py", line 34, in __init__
    cursor.execute(s)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/cursors.py", line 134, in execute
    result = self._query(query)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/cursors.py", line 282, in _query
    conn.query(q)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 768, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 929, in _read_query_result
    result.read()
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 1125, in read
    first_packet = self.connection._read_packet()
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 893, in _read_packet
    packet.check_error()
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/connections.py", line 369, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/Users/hanley/.virtualenvs/estt_8_1_ognajD/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1061, u"Duplicate key name 'access_accesscontrol_846f0221'")
```

The main thing I wonder is whether or not this is actually happening:

```
DEBUG removing access.middleware.AccessOnStart via raise MiddlewareNotUsed
```

**Comment by knabar** [comment]
This code was added to create the index on older installations - at this point every installation should have the index, so it should just go into `models.py` and the middleware needs to be deleted.

**Comment by hanleybrand** [comment]
Well rooibos log is suddenly a lot cleaner!

**Comment by hanleybrand** [comment]
> "at this point every installation should have the index so it should just go into models.py" - @knabar 

This is the first part of the AccessControl model

```python
class AccessControl(models.Model):
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField(db_index=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User, null=True, blank=True)
    usergroup = models.ForeignKey(Group, null=True, blank=True)
    read = models.NullBooleanField()
    write = models.NullBooleanField()
    manage = models.NullBooleanField()
    restrictions_repr = models.TextField(blank=True, default='')
```

`db_index = True` is already set for `AccessControl.object_id` - is that what you meant, or does the index creation logic from the middleware need to get moved into the model?

**Comment by knabar** [comment]
@hanleybrand Yes, I meant to just remove the middleware logic and be done.  New installations will get the index from the definition in `models.py`, all existing installations should have it through the middleware.

**Comment by hanleybrand** [comment]
Cool - I'll reclose the issue then -- thanks!
